<?xml version="1.0" encoding="utf-8"?><Database Name="movies" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\movies.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="moviesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.movies" Member="movies">
    <Type Name="movie">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="namee" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="genree" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="directorr" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="producerr" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="available_onn" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>